map_node:
    ros__parameters:
        map_leaf_size: 0.20
        map_topic: "/global_map"
        keyframe_topic: "/keyframe_msg"
        optimized_keyframes_topic: "/optimized_keyframes"
        rebuild_unoptimized_keyframes_with_approximation: true
        apply_pgo_correction_to_unoptimized_keyframes: true
        body_frame: "base_link"
        lidar_frame: "livox_frame"
        t_body_lidar: [-0.011, -0.02329, 0.04412]
        q_body_lidar: [1.0, 0.0, 0.0, 0.0]
        T_body_lidar:
            [
                1.0,
                0.0,
                0.0,
                -0.011,
                0.0,
                1.0,
                0.0,
                -0.02329,
                0.0,
                0.0,
                1.0,
                0.04412,
                0.0,
                0.0,
                0.0,
                1.0,
            ]
        save_map_service_name: "/save_map"
        map_save_path: "/home/goose/small_point_lio_lc/global_map.pcd"
