<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>small_point_lio_map_tools</name>
  <version>0.1.0</version>
  <description>Terrain mapping tools for Small Point-LIO point clouds.</description>
  <maintainer email="meis38@126.com">FGoose</maintainer>
  <license>MIT</license>
  <author email="meis38@126.com">FGoose</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>nav_msgs</depend>
  <depend>eigen</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
